"""create libraries and papers

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 15:34:34.690869
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_libraries_key_hash'), ['key_hash'], unique=True)

    op.create_table('papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('library_id', sa.String(length=36), nullable=True),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('arxiv_id', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_key', sa.String(length=80), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=80), nullable=True),
    sa.Column('reading', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_papers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papers_status'))
        batch_op.drop_index(batch_op.f('ix_papers_library_id'))
        batch_op.drop_index(batch_op.f('ix_papers_created_at'))

    op.drop_table('papers')
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_libraries_key_hash'))

    op.drop_table('libraries')
    # ### end Alembic commands ###
