"""questions

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 18:04:55.238229
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('library_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('answer', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_status'))
        batch_op.drop_index(batch_op.f('ix_questions_paper_id'))
        batch_op.drop_index(batch_op.f('ix_questions_library_id'))
        batch_op.drop_index(batch_op.f('ix_questions_created_at'))

    op.drop_table('questions')
    # ### end Alembic commands ###
